name: worksheet_integration
description: Example integrating worksheet_formula with the worksheet widget.
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  a1: ^2.1.0
  worksheet:
    path: ../../../../flutter/worksheet
  worksheet_formula:
    path: ../..

dev_dependencies:
  flutter_lints: ^6.0.0
